# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Jupyer To HTML

# Run every time a new commit is pushed
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Set the job key
  build:
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7]


    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: jupyter-actions
        environment-file: environment.yml
        python-version: ${{ matrix.python-version }}

    - name: build all Notebooks
      shell: bash -l {0}
      run: |
        conda activate jupyter-actions
        jupyter nbconvert GameAI.Random.ipynb --to html
        mkdir _site
        mv GameAI.Random.HTML _site/index.html

    - name: Commit files
      run: |
        rm .git -rf; cd _site ; git init
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Add changes"
        cd ../

    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        branch: gh-pages
        directory: _site
        force: true
        github_token: ${{ secrets.GITHUB_TOKEN }}